/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul_inreg_colet;

import fis.NewJFrame;
import java.awt.Color;
import java.math.RoundingMode;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modul_calcul_pret_traseu.*;

/**
 *
 * @author paulv
 */
public class formInreg extends javax.swing.JFrame {
    /*Connection conn=null;
    PreparedStatement stmt1=null;
    PreparedStatement stmt2=null;
    PreparedStatement stmt3=null;*/
    

    /**
     * Creates new form formInreg
     */
    public formInreg() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        expNume = new javax.swing.JTextField();
        expAdresa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        expTelefon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        expMail = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        expOrasCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        destNume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destAdresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        destTelefon = new javax.swing.JTextField();
        destMail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destOrasCombo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        colCod = new javax.swing.JTextField();
        colGreutate = new javax.swing.JTextField();
        btnGenerateCode = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        colCategorie = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        colPret = new javax.swing.JTextField();
        btnCalculatePrice = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inregistrare colet");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setName("Inregistrare colet"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 210, 53));
        jLabel19.setText("Inregistrare colet");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nume:");

        expNume.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        expNume.setForeground(new java.awt.Color(51, 0, 102));

        expAdresa.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        expAdresa.setForeground(new java.awt.Color(51, 0, 102));
        expAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expAdresaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Adresa:");

        jLabel12.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Oras:");

        expTelefon.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        expTelefon.setForeground(new java.awt.Color(51, 0, 102));
        expTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expTelefonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mail");

        expMail.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        expMail.setForeground(new java.awt.Color(51, 0, 102));
        expMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expMailActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Telefon:");

        jLabel9.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Date expeditor");

        expOrasCombo.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        expOrasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alegeti orasul", "Arad", "Caransebes ", "Cluj Napoca", "Lugoj", "Marghita", "Oradea", "Orsova", "Resita", "Salonta", "Timisoara", "Zalau" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expNume, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expMail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(expOrasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(expAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(expOrasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(expTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(expMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 410, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        destNume.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        destNume.setForeground(new java.awt.Color(51, 0, 102));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nume:");

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adresa:");

        destAdresa.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        destAdresa.setForeground(new java.awt.Color(51, 0, 102));
        destAdresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destAdresaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oras:");

        jLabel6.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Telefon:");

        destTelefon.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        destTelefon.setForeground(new java.awt.Color(51, 0, 102));
        destTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTelefonActionPerformed(evt);
            }
        });

        destMail.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        destMail.setForeground(new java.awt.Color(51, 0, 102));
        destMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destMailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mail");

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date destinatar");

        destOrasCombo.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        destOrasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alegeti orasul", "Arad", "Caransebes ", "Cluj Napoca", "Lugoj", "Marghita", "Oradea", "Orsova", "Resita", "Salonta", "Timisoara", "Zalau" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destNume, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destMail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destOrasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destNume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destOrasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(destAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(destTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(destMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 210, 53));

        jLabel15.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel15.setText("Greutate:");

        jLabel16.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel16.setText("Cod pachet:");

        colCod.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        colCod.setForeground(new java.awt.Color(51, 0, 102));
        colCod.setEnabled(false);

        colGreutate.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        colGreutate.setForeground(new java.awt.Color(51, 0, 102));

        btnGenerateCode.setBackground(new java.awt.Color(0, 0, 0));
        btnGenerateCode.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnGenerateCode.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateCode.setText("Generare Cod");
        btnGenerateCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateCodeActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel17.setText("Categorie:");

        colCategorie.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        colCategorie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nu se aplica", "Fragil", "Periculos", "Pretios" }));

        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel18.setText("Preț:");

        colPret.setEditable(false);
        colPret.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        colPret.setForeground(new java.awt.Color(51, 0, 102));

        btnCalculatePrice.setBackground(new java.awt.Color(0, 0, 0));
        btnCalculatePrice.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnCalculatePrice.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculatePrice.setText("Calculare pret");
        btnCalculatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculatePriceActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        jLabel14.setText("Detalii colet");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colPret, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculatePrice))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colCod, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGenerateCode))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colGreutate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(colGreutate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(colCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateCode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(colCategorie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(colPret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculatePrice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 410, -1));

        btnClear.setBackground(new java.awt.Color(0, 0, 0));
        btnClear.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 66, -1));

        btnAdd.setBackground(new java.awt.Color(255, 210, 53));
        btnAdd.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnAdd.setText("Adaugare colet");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 143, -1));

        jLabel21.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 210, 53));
        jLabel21.setText("Curier");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inapoi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void destAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destAdresaActionPerformed

    private void destTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTelefonActionPerformed

    private void destMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destMailActionPerformed

    private void expAdresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expAdresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expAdresaActionPerformed

    private void expMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expMailActionPerformed

    private void expTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expTelefonActionPerformed

    private void btnGenerateCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateCodeActionPerformed
        colCod.setText(Pachet.asignCod());
    }//GEN-LAST:event_btnGenerateCodeActionPerformed

    private boolean Verificare(){
        try{
        if(!Verify.verifyNume(destNume.getText())){
            throw new Exception("Nume destinatar: format gresit!");  
        }
        if(!Verify.verifyNume(expNume.getText())){
            throw new Exception("Nume expeditor: format gresit!");
        }
        if(!Verify.verifyMail(destMail.getText())){
            throw new Exception("Mail destinatar: format gresit!");
        }
        if(!Verify.verifyMail(expMail.getText())){
            throw new Exception("Mail expeditor: format gresit!");
        }
        if(!Verify.verifyTelefon(destTelefon.getText())){
            throw new Exception("Telefon destinatar: format gresit!");
        }
        if(!Verify.verifyTelefon(expTelefon.getText())){
           throw new Exception("Telefon expeditor: format gresit!");
        }
        
        if(destOrasCombo.getSelectedIndex()==0){
            throw new Exception("Oras destinatar: format gresit!");
        }
        if(expOrasCombo.getSelectedIndex()==0){
             throw new Exception("Oras expeditor: format gresit!");
        }
        
        if(!Verify.verifyCod(colCod.getText())){
             throw new Exception("Cod colet negenerat!");
        }
        if(!Verify.verifyNrNegativ(Float.parseFloat(colPret.getText()))){
            throw new Exception("Pret necalculat!");
        }
        if(!Verify.verifyNrNegativ(Float.parseFloat(colGreutate.getText()))){
            throw new Exception("Greutatea nu a fost introdusa!");
        }
        return true;
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            return false;
        }
    }
    
    private void setTextEmpty(){
            destNume.setText("");
            destAdresa.setText("");
            destOrasCombo.setSelectedIndex(0);
            destTelefon.setText("");
            destMail.setText("");
            expNume.setText("");
            expAdresa.setText("");
            expOrasCombo.setSelectedItem("Alegeti orasul");
            expTelefon.setText("");
            expMail.setText("");
            colCod.setText("");
            colGreutate.setText("");
            colPret.setText("");
            
            destNume.setBackground(Color.WHITE);
            destAdresa.setBackground(Color.WHITE);
           
            destTelefon.setBackground(Color.WHITE);
            destMail.setBackground(Color.WHITE);
            expNume.setBackground(Color.WHITE);
            expAdresa.setBackground(Color.WHITE);
       
            expTelefon.setBackground(Color.WHITE);
            expMail.setBackground(Color.WHITE);
            colCod.setBackground(Color.WHITE);
            colGreutate.setBackground(Color.WHITE);
            colPret.setBackground(Color.WHITE);
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        try{
            
            //Persoana pExp = null;
            
            Date date = new Date();
            
            if(Verificare()==false)
                throw new Exception("Format gresit");
            Persoana pDest = new Persoana(destNume.getText(), destAdresa.getText(),destOrasCombo.getSelectedItem().toString(),destTelefon.getText(),destMail.getText());
            Persoana pExp = new Persoana(expNume.getText(), expAdresa.getText(),expOrasCombo.getSelectedItem().toString(),expTelefon.getText(),expMail.getText());
            Pachet pk=new Pachet(pExp, pDest, Float.parseFloat(colGreutate.getText()), colCod.getText(), colCategorie.getSelectedItem().toString(), Float.parseFloat(colPret.getText()),destOrasCombo.getSelectedItem().toString(),"", date);
            String info="Confirmare comanda\n Cod comanda:"+pk.getCod()
                    +"\n\nInformatii destinatar: \n"
                    +pDest.Nume+"\n"+pDest.Adresa
                    +"\n"+pDest.Oras+"\n"+pDest.numarTelefon
                    +"\n"+pDest.Mail
                    +"\n\nInformatii expeditor: \n"
                    +pExp.Nume+"\n"+pExp.Adresa
                    +"\n"+pExp.Oras+"\n"+pExp.numarTelefon
                    +"\n"+pExp.Mail
                    +"\n\nInformatii colet: \n"+pk.getGreutate()
                    +" kg\n"+pk.getCategorie()+"\n"+pk.pret
                    +"\n\nAsteptare confirmare!\n";
            System.out.println(info);
            new Confirmation(info,pDest,pExp,pk).setVisible(true);
            setTextEmpty();
            //dispose();
        } catch (NumberFormatException | SQLException ex ) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(formInreg.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        setTextEmpty();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCalculatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculatePriceActionPerformed
        Double pret;
        DecimalFormat df = new DecimalFormat("#.##");
        df.setRoundingMode(RoundingMode.CEILING);
        calculRute.calculareTraseu(destOrasCombo.getSelectedItem().toString(), expOrasCombo.getSelectedItem().toString(), colCategorie.getSelectedItem().toString());
        pret=Pret.calculPret(calculRute.getKilometrii(),colCategorie.getSelectedItem().toString(),Float.parseFloat(colGreutate.getText()));
      
        colPret.setText(df.format(pret));
    }//GEN-LAST:event_btnCalculatePriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        NewJFrame njf= new NewJFrame();
        njf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formInreg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new formInreg().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCalculatePrice;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnGenerateCode;
    private javax.swing.JComboBox<String> colCategorie;
    private javax.swing.JTextField colCod;
    private javax.swing.JTextField colGreutate;
    private javax.swing.JTextField colPret;
    private javax.swing.JTextField destAdresa;
    private javax.swing.JTextField destMail;
    private javax.swing.JTextField destNume;
    private javax.swing.JComboBox<String> destOrasCombo;
    private javax.swing.JTextField destTelefon;
    private javax.swing.JTextField expAdresa;
    private javax.swing.JTextField expMail;
    private javax.swing.JTextField expNume;
    private javax.swing.JComboBox<String> expOrasCombo;
    private javax.swing.JTextField expTelefon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
