/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul_destinatie;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import modul_inreg_colet.*;
import java.text.DateFormat;  
import java.text.ParseException;
import java.text.SimpleDateFormat;  
import java.util.Date;  
import java.util.Calendar;  
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alinb
 */
public class sediu extends javax.swing.JFrame {

    Date d=new Date();
    Persoana dest=new Persoana("","","","","");
    Persoana exp=new Persoana("","","","","");
    Pachet pachet= new Pachet(exp, dest,2, "","", 3, "", "" , d);
    Transport t=new Transport();
    Destinatie destinatie=new Destinatie();
    
    /**
     * Creates new form sediu
     */
    public sediu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRetur = new javax.swing.JButton();
        txtStare = new javax.swing.JTextField();
        btnColet = new javax.swing.JButton();
        lblZile = new javax.swing.JLabel();
        lblStare = new javax.swing.JLabel();
        txtNume = new javax.swing.JTextField();
        btnCauta = new javax.swing.JButton();
        btnRidicat = new javax.swing.JButton();
        txtZile = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnContactExp = new javax.swing.JButton();
        txtNumeExp = new javax.swing.JTextField();
        txtTelExp = new javax.swing.JTextField();
        lblTelExp = new javax.swing.JLabel();
        lblNumeExp = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnContactDest = new javax.swing.JButton();
        lblNumeDest = new javax.swing.JLabel();
        lblTelDest = new javax.swing.JLabel();
        txtTelDest = new javax.swing.JTextField();
        txtNumeDest = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        comboLocatie = new javax.swing.JComboBox<>();
        btnUpdateLocatie = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnUpdateStare = new javax.swing.JButton();
        comboStare = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 210, 53));
        jLabel20.setText("Curier");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Montserrat Light", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 210, 53));
        jLabel19.setText("Administrator");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numele destinatarului");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 137, -1));

        btnRetur.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnRetur.setText("Retur");
        btnRetur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturActionPerformed(evt);
            }
        });
        jPanel2.add(btnRetur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        txtStare.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtStare.setEnabled(false);
        jPanel2.add(txtStare, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 258, -1));

        btnColet.setBackground(new java.awt.Color(0, 0, 0));
        btnColet.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnColet.setForeground(new java.awt.Color(255, 255, 255));
        btnColet.setText("Mergi catre Inregistrare colet");
        btnColet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColetActionPerformed(evt);
            }
        });
        jPanel2.add(btnColet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 200, -1));

        lblZile.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblZile.setForeground(new java.awt.Color(255, 255, 255));
        lblZile.setText("zile trecute");
        jPanel2.add(lblZile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        lblStare.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblStare.setForeground(new java.awt.Color(255, 255, 255));
        lblStare.setText("stare pachet");
        jPanel2.add(lblStare, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txtNume.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        jPanel2.add(txtNume, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 200, -1));

        btnCauta.setBackground(new java.awt.Color(255, 210, 53));
        btnCauta.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnCauta.setText("Cauta colet");
        btnCauta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCautaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCauta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        btnRidicat.setBackground(new java.awt.Color(255, 210, 53));
        btnRidicat.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnRidicat.setText("Pachet Ridicat");
        btnRidicat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRidicatActionPerformed(evt);
            }
        });
        jPanel2.add(btnRidicat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        txtZile.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtZile.setEnabled(false);
        jPanel2.add(txtZile, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 258, -1));

        jPanel3.setBackground(new java.awt.Color(255, 210, 53));

        btnContactExp.setBackground(new java.awt.Color(0, 0, 0));
        btnContactExp.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnContactExp.setForeground(new java.awt.Color(255, 255, 255));
        btnContactExp.setText("Contactare expeditor");
        btnContactExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactExpActionPerformed(evt);
            }
        });

        txtNumeExp.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtNumeExp.setEnabled(false);

        txtTelExp.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtTelExp.setEnabled(false);

        lblTelExp.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblTelExp.setText("Telefon");

        lblNumeExp.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblNumeExp.setText("Nume");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContactExp)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelExp)
                            .addComponent(lblNumeExp))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTelExp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeExp, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContactExp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelExp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 240, 110));

        jPanel4.setBackground(new java.awt.Color(255, 210, 53));

        btnContactDest.setBackground(new java.awt.Color(0, 0, 0));
        btnContactDest.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnContactDest.setForeground(new java.awt.Color(255, 255, 255));
        btnContactDest.setText("Contactare destinatar");
        btnContactDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactDestActionPerformed(evt);
            }
        });

        lblNumeDest.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblNumeDest.setText("Nume");

        lblTelDest.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        lblTelDest.setText("Telefon");

        txtTelDest.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtTelDest.setEnabled(false);

        txtNumeDest.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        txtNumeDest.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContactDest)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblNumeDest)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumeDest, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblTelDest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelDest, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnContactDest)
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeDest)
                    .addComponent(txtNumeDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelDest)
                    .addComponent(txtTelDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 220, 110));

        jPanel5.setBackground(new java.awt.Color(255, 210, 53));

        comboLocatie.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        comboLocatie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alege locatia", "Arad", "Caransebes ", "Cluj Napoca", "Lugoj", "Marghita", "Oradea", "Orsova", "Resita", "Salonta", "Timisoara", "Zalau" }));

        btnUpdateLocatie.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnUpdateLocatie.setText("Update locatie");
        btnUpdateLocatie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLocatieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboLocatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLocatie))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(comboLocatie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateLocatie)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, 70));

        jPanel6.setBackground(new java.awt.Color(255, 210, 53));

        btnUpdateStare.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        btnUpdateStare.setText("Update stare");
        btnUpdateStare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStareActionPerformed(evt);
            }
        });

        comboStare.setFont(new java.awt.Font("Montserrat", 0, 11)); // NOI18N
        comboStare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "alege starea", "in tranzit", "in asteptare", "in tranzit retur", "in posesia firmei" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(comboStare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnUpdateStare)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboStare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdateStare)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 550, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateStareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStareActionPerformed
        // TODO add your handling code here:
      pachet.setStare(comboStare.getSelectedItem().toString());
     txtStare.setText(comboStare.getSelectedItem().toString());
    if(pachet.getStare().equals("in asteptare"))
                                txtZile.setText(Long.toString(destinatie.pornireTimer(pachet)));
                                else
                                    txtZile.setText("coletul inca nu a ajuns la destinatie");
     t.updateStare(pachet);
        
    }//GEN-LAST:event_btnUpdateStareActionPerformed

    private void btnRidicatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRidicatActionPerformed
        // TODO add your handling code here:
         try{
         String url = "jdbc:mysql://localhost:3306/registration_details";
	Statement sql;
        Statement sql1;
        Statement sql2;
	ResultSet rs;
        ResultSet rs1;
        ResultSet rs2;
	Connection con1 = DriverManager.getConnection(url, "root", "anglia");
	sql = (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        sql1 = (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        sql2= (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
	rs = sql.executeQuery("select * from packages");
        rs1 = sql1.executeQuery("select * from dest_person");
        rs2 = sql2.executeQuery("select * from exp_person");
        rs.next();
        rs1.next();
        rs2.next();
        String nume= new String();
        nume= txtNume.getText();
        
        boolean found = false;
        boolean found1 = false;
        boolean found2 = false;
		do {
			if (nume.equals(rs.getString("nume_dest"))){
                               
                                do{
                                    if(pachet.getDestinatar().equals(rs1.getString("nume")))
                                    {
                                        rs1.deleteRow();
                                        found1= true;
                                    }
                                    else
                                    {
                                        rs1.next();
                                    }
                                }while(!found1);
                                
                                do{
                                    if(pachet.getExpeditor().equals(rs2.getString("nume")))
                                    {
                                        
                                        rs2.deleteRow();
                                        found2=true;
                                    }
                                    else
                                    {
                                        rs2.next();
                                    }
                                }while(!found2);
                               
                           
                                rs.deleteRow();
				found = true;
			} else
                            rs.next();
                    } while (!found);
                txtNume.setText("");
                txtStare.setText("");
                txtZile.setText("");
                txtNumeDest.setText("");
                txtTelDest.setText("");
                txtNumeExp.setText("");
                txtTelExp.setText("");
                comboStare.setSelectedIndex(0);
                comboLocatie.setSelectedIndex(0);
        
     }
     catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
    }//GEN-LAST:event_btnRidicatActionPerformed

    private void btnCautaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCautaActionPerformed
        // TODO add your handling code here:
             try{
         String url = "jdbc:mysql://localhost:3306/registration_details";
	Statement sql;
        Statement sql1;
        Statement sql2;
	ResultSet rs;
        ResultSet rs1;
        ResultSet rs2;
	Connection con1 = DriverManager.getConnection(url, "root", "anglia");
	sql = (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        sql1 = (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        sql2= (Statement) con1.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
	rs = sql.executeQuery("select * from packages");
        rs1 = sql1.executeQuery("select * from dest_person");
        rs2 = sql2.executeQuery("select * from exp_person");
        rs.next();
        rs1.next();
        rs2.next();
        String nume= new String();
        nume= txtNume.getText();
        
        boolean found = false;
        boolean found1 = false;
        boolean found2 = false;
      
		do {
			if (nume.equals(rs.getString("nume_dest"))) {
                            
				txtStare.setText(rs.getString("stare"));
                             
                                pachet.setData(rs.getString("data_destinatie"));
                                pachet.setStare(rs.getString("stare"));
                             
                                dest.setNume(rs.getString("nume_dest"));
                                exp.setNume(rs.getString("nume_exp"));
                                
                                do{
                                    if(nume.equals(rs1.getString("nume")))
                                    {
                                        dest.setAdresa(rs1.getString("adresa"));
                                        dest.setMail(rs1.getString("mail"));
                                        dest.setTelefon(rs1.getString("telefon"));
                                        dest.setOras(rs1.getString("oras"));
                                      
                                        found1=true;
                                    }
                                    else
                                    {
                                        rs1.next();
                                    }
                                }while(!found1);
                                
                               
                                do{
                                    if(rs.getString("nume_exp").equals(rs2.getString("nume")))
                                    {
                                          exp.setAdresa(rs2.getString("adresa"));
                                        exp.setMail(rs2.getString("mail"));
                                        exp.setTelefon(rs2.getString("telefon"));
                                        exp.setOras(rs1.getString("oras"));
                                 
                                        found2=true;
                                    }
                                    else
                                    {
                                        rs2.next();
                                    }
                                }while(!found2);
                               
                                   if(pachet.getStare().equals("in asteptare"))
                                    txtZile.setText(Long.toString(destinatie.pornireTimer(pachet)));
                                else
                                    txtZile.setText("coletul inca nu a ajuns la destinatie");
                                pachet.setPret(rs.getFloat("pret"));
                                pachet.setDestinatar(dest);
                                pachet.setExpeditor(exp);
                             
				found = true;
			} else
                            rs.next();
                    } while (!found);
        
     }
     catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(sediu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCautaActionPerformed

    private void btnContactDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactDestActionPerformed
        // TODO add your handling code here:
        txtNumeDest.setText(pachet.getDestinatar());
        txtTelDest.setText(dest.getTelefon());
    }//GEN-LAST:event_btnContactDestActionPerformed

    private void btnContactExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactExpActionPerformed
        // TODO add your handling code here:
        txtNumeExp.setText(pachet.getExpeditor());
        txtTelExp.setText(exp.getTelefon());
        
    }//GEN-LAST:event_btnContactExpActionPerformed

    private void btnUpdateLocatieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLocatieActionPerformed
        // TODO add your handling code here:
         pachet.setLocatieCurenta(comboLocatie.getSelectedItem().toString());
         t.updateLocatie(pachet);
    }//GEN-LAST:event_btnUpdateLocatieActionPerformed

    private void btnReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturActionPerformed
      
       
            // TODO add your handling code here:
            destinatie.retur(pachet, dest, exp);
       
            txtStare.setText("");
            txtZile.setText("");
            txtNume.setText("");
            txtNumeDest.setText("");
            txtTelDest.setText("");
            txtNumeExp.setText("");
            txtTelExp.setText("");
               
                comboStare.setSelectedIndex(0);
                comboLocatie.setSelectedIndex(0);
       
    }//GEN-LAST:event_btnReturActionPerformed

    private void btnColetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColetActionPerformed
        // TODO add your handling code here:
             dispose();
        formInreg frm= new formInreg();
        frm.setVisible(true);
    }//GEN-LAST:event_btnColetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sediu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sediu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sediu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sediu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sediu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCauta;
    private javax.swing.JButton btnColet;
    private javax.swing.JButton btnContactDest;
    private javax.swing.JButton btnContactExp;
    private javax.swing.JButton btnRetur;
    private javax.swing.JButton btnRidicat;
    private javax.swing.JButton btnUpdateLocatie;
    private javax.swing.JButton btnUpdateStare;
    private javax.swing.JComboBox<String> comboLocatie;
    private javax.swing.JComboBox<String> comboStare;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblNumeDest;
    private javax.swing.JLabel lblNumeExp;
    private javax.swing.JLabel lblStare;
    private javax.swing.JLabel lblTelDest;
    private javax.swing.JLabel lblTelExp;
    private javax.swing.JLabel lblZile;
    private javax.swing.JTextField txtNume;
    private javax.swing.JTextField txtNumeDest;
    private javax.swing.JTextField txtNumeExp;
    private javax.swing.JTextField txtStare;
    private javax.swing.JTextField txtTelDest;
    private javax.swing.JTextField txtTelExp;
    private javax.swing.JTextField txtZile;
    // End of variables declaration//GEN-END:variables

    private String dateFormat(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
